window.CATALOG_PRODUCTS = [
  {
    "id": 1,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Anklet Socks",
    "description": "Premium Ankle Socks",
    "material": "Polyester Nylon Blend",
    "size": "S - XL; Above Ankle 10cm - 14cm",
    "moq": "30 Pairs",
    "page": 3,
    "image": "images/catalog/socks-anklet-socks.jpg"
  },
  {
    "id": 2,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Knee High Socks",
    "description": "Premium Socks That Fit Under The Knee",
    "material": "Polyester Nylon Blend",
    "size": "S - L; Under The Knee",
    "moq": "30 Pairs",
    "page": 4,
    "image": "images/catalog/socks-knee-high-socks.jpg"
  },
  {
    "id": 3,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Casual Crew Socks",
    "description": "Relaxed Fit, One Size, Flat-Seamed Toe",
    "material": "Polyester Nylon Blend",
    "size": "One Size; Under Calf 14cm - 18cm",
    "moq": "30 Pairs",
    "page": 5,
    "image": "images/catalog/socks-casual-crew-socks.jpg"
  },
  {
    "id": 4,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Premium Crew Socks",
    "description": "Premium Sport, Leisure And Everyday Socks",
    "material": "Polyester Nylon Blend",
    "size": "XS - XL; Under Calf 12cm - 18cm",
    "moq": "30 Pairs",
    "page": 6,
    "image": "images/catalog/socks-premium-crew-socks.jpg"
  },
  {
    "id": 5,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Ribbed Crew Socks",
    "description": "Relaxed Fit And Ribbed Texture",
    "material": "Polyester Nylon Blend",
    "size": "S- XL; Under Calf 14cm - 18cm",
    "moq": "30 Pairs",
    "page": 7,
    "image": "images/catalog/socks-ribbed-crew-socks.jpg"
  },
  {
    "id": 6,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Wool Crew Socks",
    "description": "Premium Sport, Leisure And Everyday Socks",
    "material": "Wool Blend",
    "size": "M - L; Under Calf 12cm - 18cm",
    "moq": "30 Pairs",
    "page": 8,
    "image": "images/catalog/socks-wool-crew-socks.jpg"
  },
  {
    "id": 7,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Tab Socks",
    "description": "Premium Short Socks",
    "material": "Polyester Nylon Blend",
    "size": "S - XL; 2cm Above Shoe",
    "moq": "30 Pairs",
    "page": 9,
    "image": "images/catalog/socks-tab-socks.jpg"
  },
  {
    "id": 8,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Sport Socks",
    "description": "Premium Socks Made To Wear With Shin Guards",
    "material": "Polyester Nylon Blend",
    "size": "S - L; Under The Knee",
    "moq": "30 Pairs",
    "page": 10,
    "image": "images/catalog/socks-sport-socks.jpg"
  },
  {
    "id": 9,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Leg Sleeves",
    "description": "Premium Leg Sleeves Made To Wear With Shin Guards",
    "material": "Polyester Nylon Blend",
    "size": "One Size; Above Ankle 45cm - 47cm",
    "moq": "30 Pairs",
    "page": 11,
    "image": "images/catalog/socks-leg-sleeves.jpg"
  },
  {
    "id": 10,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Arm Sleeves With Spf 50+ UV Resistance",
    "description": "(Tested And Certified By Cansa)",
    "material": "Polyester Nylon Blend",
    "size": "M - L; Bicep To Wrist",
    "moq": "30 Pairs",
    "page": 12,
    "image": "images/catalog/socks-arm-sleeves-with-spf-50-uv-resistance.jpg"
  },
  {
    "id": 11,
    "source": "Custom Branded Socks Catalogue.pdf",
    "category": "Socks and Sleeves",
    "name": "Sweat Bands",
    "description": "Perfect For Activities Such As Gym, Crossfit & Tennis",
    "material": "Polyester Nylon Blend",
    "size": "One Size; 17cm Above Wrist",
    "moq": "30 Pairs",
    "page": 13,
    "image": "images/catalog/socks-sweat-bands.jpg"
  },
  {
    "id": 12,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Umhlanga Drawstring Bag",
    "description": "Purple",
    "material": "100% Polyester",
    "size": "310 x 405mm (L x H)",
    "moq": "100 Units",
    "page": 6,
    "image": "images/catalog/bags-umhlanga-drawstring-bag.jpg"
  },
  {
    "id": 13,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Cuba Drawstring Bag",
    "description": "Cuba Upstyled",
    "material": "170gsm",
    "size": "200 x 280mm (L x H)",
    "moq": "75 Units",
    "page": 7,
    "image": "images/catalog/bags-cuba-drawstring-bag.jpg"
  },
  {
    "id": 14,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Bahamas Drawstring Bag",
    "description": "Bahamas Upstyled",
    "material": "170gsm",
    "size": "310 x 405mm (L x H)",
    "moq": "75 Units",
    "page": 8,
    "image": "images/catalog/bags-bahamas-drawstring-bag.jpg"
  },
  {
    "id": 15,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Tahiti Drawstring Bag",
    "description": "Tahiti Upstyled",
    "material": "170gsm",
    "size": "310 x 405mm (L x H)",
    "moq": "75 Units",
    "page": 9,
    "image": "images/catalog/bags-tahiti-drawstring-bag.jpg"
  },
  {
    "id": 16,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Centurion Shopper Bag",
    "description": "Navy Blue",
    "material": "SpunBond",
    "size": "320 x 350 x 105mm (L x H x W)",
    "moq": "100 Units",
    "page": 10,
    "image": "images/catalog/bags-centurion-shopper-bag.jpg"
  },
  {
    "id": 17,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Via Dei Condotti Carrier Bag",
    "description": "Via Dei Condotti Upstyled",
    "material": "170gsm",
    "size": "300 x 250 x 70mm (L x H x W)",
    "moq": "75 Units",
    "page": 11,
    "image": "images/catalog/bags-via-dei-condotti-carrier-bag.jpg"
  },
  {
    "id": 18,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Kew Crossbody Bag",
    "description": "Bramley Upstyled",
    "material": "D600 And 170gsm",
    "size": "200 x 210 x 60mm (L x H x W)",
    "moq": "75 Units",
    "page": 12,
    "image": "images/catalog/bags-kew-crossbody-bag.jpg"
  },
  {
    "id": 19,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Bramley Crossbody Bag",
    "description": "Bramley Upstyled",
    "material": "D600 And 170gsm",
    "size": "200 x 210 x 60mm (L x H x W)",
    "moq": "75 Units",
    "page": 13,
    "image": "images/catalog/bags-bramley-crossbody-bag.jpg"
  },
  {
    "id": 20,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Istanbul Mini Crossbody Bag",
    "description": "Istanbul Upstyled",
    "material": "D600 And 170gsm",
    "size": "150 x 245 x 60mm (L x H x W)",
    "moq": "75 Units",
    "page": 14,
    "image": "images/catalog/bags-istanbul-mini-crossbody-bag.jpg"
  },
  {
    "id": 21,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Chicago Crossbody Conference Bag",
    "description": "Chicago Upstyled",
    "material": "D600 And 170gsm",
    "size": "250 x 320 x 70mm (L x H x W)",
    "moq": "75 Units",
    "page": 15,
    "image": "images/catalog/bags-chicago-crossbody-conference-bag.jpg"
  },
  {
    "id": 22,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Accra Crossbody Bag",
    "description": "Accra Upstyled",
    "material": "D600 And 170gsm",
    "size": "155 x 210 x 40mm (L x H x W)",
    "moq": "75 Units",
    "page": 16,
    "image": "images/catalog/bags-accra-crossbody-bag.jpg"
  },
  {
    "id": 23,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Austria Crossbody Bag",
    "description": "Austria Upstyled",
    "material": "D600 And 170gsm",
    "size": "250 x 250 x 70mm (L x H x W)",
    "moq": "75 Units",
    "page": 17,
    "image": "images/catalog/bags-austria-crossbody-bag.jpg"
  },
  {
    "id": 24,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Brisbane Maxi Crossbody Bag",
    "description": "Brisbane Maxi Upstyled",
    "material": "D600 And 170gsm",
    "size": "220 x 340 x 60mm (L x H x W)",
    "moq": "75 Units",
    "page": 18,
    "image": "images/catalog/bags-brisbane-maxi-crossbody-bag.jpg"
  },
  {
    "id": 25,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Norway Waist Bag",
    "description": "Norway Upstyled",
    "material": "170gsm",
    "size": "260 x 110mm (L x W)",
    "moq": "75 Units",
    "page": 19,
    "image": "images/catalog/bags-norway-waist-bag.jpg"
  },
  {
    "id": 26,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Oslo Waist Bag",
    "description": "Oslo Upstyled",
    "material": "170gsm",
    "size": "220 x 140mm (L x H)",
    "moq": "75 Units",
    "page": 20,
    "image": "images/catalog/bags-oslo-waist-bag.jpg"
  },
  {
    "id": 27,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Porto Waist Bag",
    "description": "Porto Upstyled",
    "material": "170gsm",
    "size": "200 x 140 x 50mm (L x H x W)",
    "moq": "75 Units",
    "page": 21,
    "image": "images/catalog/bags-porto-waist-bag.jpg"
  },
  {
    "id": 28,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Toronto Waist Bag",
    "description": "Toronto Upstyled",
    "material": "170gsm",
    "size": "350 x 140mm (L x H)",
    "moq": "75 Units",
    "page": 22,
    "image": "images/catalog/bags-toronto-waist-bag.jpg"
  },
  {
    "id": 29,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Fairview Insulated Wine Cooler",
    "description": "Fairview Upstyled",
    "material": "D600 And 170gsm",
    "size": "215 x 310 x 100mm (L x H x W)",
    "moq": "75 Units",
    "page": 23,
    "image": "images/catalog/bags-fairview-insulated-wine-cooler.jpg"
  },
  {
    "id": 30,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Hogsback 16 Can Cooler",
    "description": "Hogsback Upstyled",
    "material": "D600 And 170gsm",
    "size": "230 x 310 x 120mm (L x H x W)",
    "moq": "75 Units",
    "page": 24,
    "image": "images/catalog/bags-hogsback-16-can-cooler.jpg"
  },
  {
    "id": 31,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Prague 6 Can Cooler",
    "description": "Prague Upstyled",
    "material": "D600 And 170gsm",
    "size": "200 x 160 x 135mm (L x H x W)",
    "moq": "75 Units",
    "page": 25,
    "image": "images/catalog/bags-prague-6-can-cooler.jpg"
  },
  {
    "id": 32,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Alaska 12 Can Cooler",
    "description": "Alaska Upstyled",
    "material": "D600, 170gsm Waterproof Coated -",
    "size": "240 x 210 x 165mm (L x H x W)",
    "moq": "75 Units",
    "page": 26,
    "image": "images/catalog/bags-alaska-12-can-cooler.jpg"
  },
  {
    "id": 33,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Siberia Lunch Cooler",
    "description": "Siberia Upstyled",
    "material": "170gsm",
    "size": "Open  350 x 320 x 165mm (L x H x W)",
    "moq": "75 Units",
    "page": 27,
    "image": "images/catalog/bags-siberia-lunch-cooler.jpg"
  },
  {
    "id": 34,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Molteno Lunch Cooler",
    "description": "Molteno",
    "material": "170gsm",
    "size": "300 x 80 x 165mm (L x H x W)",
    "moq": "75 Units",
    "page": 28,
    "image": "images/catalog/bags-molteno-lunch-cooler.jpg"
  },
  {
    "id": 35,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Santa Monica Picnic Cooler",
    "description": "Santa Monica Upstyled",
    "material": "170gsm",
    "size": "520 x 380 x 190mm (L x H x W)",
    "moq": "75 Units",
    "page": 29,
    "image": "images/catalog/bags-santa-monica-picnic-cooler.jpg"
  },
  {
    "id": 36,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Malibu Lunch Cooler",
    "description": "Malibu Upstyled",
    "material": "170gsm",
    "size": "320 x 240 x 110mm (L x H x W)",
    "moq": "75 Units",
    "page": 30,
    "image": "images/catalog/bags-malibu-lunch-cooler.jpg"
  },
  {
    "id": 37,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Tampa Insulated Maxi Cooler",
    "description": "Tampa Maxi Upstyled",
    "material": "D600 And 170gsm",
    "size": "250 x 200 x 100mm (L x H x W)",
    "moq": "50 Units",
    "page": 31,
    "image": "images/catalog/bags-tampa-insulated-maxi-cooler.jpg"
  },
  {
    "id": 38,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "The New Yorker XL Insulated Cooler",
    "description": "New Yorker XL Upstyled",
    "material": "D600 And 170gsm",
    "size": "500 x 220 x 360mm (L x H x W)",
    "moq": "",
    "page": 32,
    "image": "images/catalog/bags-the-new-yorker-xl-insulated-cooler.jpg"
  },
  {
    "id": 39,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Detroit Insulated Round Cooler",
    "description": "Detroit Upstyled",
    "material": "D600 And 170gsm",
    "size": "200 x 200 x 110mm (L x H x W)",
    "moq": "50 Units",
    "page": 33,
    "image": "images/catalog/bags-detroit-insulated-round-cooler.jpg"
  },
  {
    "id": 40,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Wynberg Insulated Lunch Cooler",
    "description": "Wynberg Upstyled",
    "material": "D600 And 170gsm",
    "size": "230 x 85 x 200mm (L x H x W)",
    "moq": "75 Units",
    "page": 34,
    "image": "images/catalog/bags-wynberg-insulated-lunch-cooler.jpg"
  },
  {
    "id": 41,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "St. Peter Backpack",
    "description": "St. Peter Upstyled",
    "material": "D600 And 170gsm",
    "size": "315 x 350 x 125mm (L x H x W)",
    "moq": "75 Units",
    "page": 35,
    "image": "images/catalog/bags-st-peter-backpack.jpg"
  },
  {
    "id": 42,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "St. Anthony Backpack",
    "description": "St. Anthony Upstyled",
    "material": "D600 And 170gsm",
    "size": "310 x 420 x 125mm (L x H x W)",
    "moq": "75 Units",
    "page": 36,
    "image": "images/catalog/bags-st-anthony-backpack.jpg"
  },
  {
    "id": 43,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Single Compartment School Backpack",
    "description": "St. Ann Water-Resistant",
    "material": "D600 And 170gsm",
    "size": "300 x 400 x 130mm (L x H x W)",
    "moq": "50 Units",
    "page": 37,
    "image": "images/catalog/bags-single-compartment-school-backpack.jpg"
  },
  {
    "id": 44,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "St. Claire Nurses Pouch",
    "description": "St. Claire Upstyled",
    "material": "170gsm",
    "size": "135 x 200mm (L x H)",
    "moq": "75 Units",
    "page": 38,
    "image": "images/catalog/bags-st-claire-nurses-pouch.jpg"
  },
  {
    "id": 45,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "St. Paul Extra Long Pencil Case",
    "description": "St. Paul Upstyled",
    "material": "170gsm",
    "size": "400 x 120mm (L x H)",
    "moq": "75 Units",
    "page": 39,
    "image": "images/catalog/bags-st-paul-extra-long-pencil-case.jpg"
  },
  {
    "id": 46,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "St. Catherine School Chair Bag",
    "description": "St. Cathrine",
    "material": "D600 And 170gsm",
    "size": "390 x 500mm (L x H)",
    "moq": "50 Units",
    "page": 40,
    "image": "images/catalog/bags-st-catherine-school-chair-bag.jpg"
  },
  {
    "id": 47,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Nairobi Tech Sleeve - 15.6\u201d",
    "description": "Nairobi - 15.6\u201d Upstyled",
    "material": "170gsm",
    "size": "15.6-inch",
    "moq": "75 Units",
    "page": 41,
    "image": "images/catalog/bags-nairobi-tech-sleeve-15-6.jpg"
  },
  {
    "id": 48,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Abuja Tech Sleeve - 17\u201d",
    "description": "Abuja - 17\u201d Upstyled",
    "material": "D600 And 170gsm",
    "size": "17-inch",
    "moq": "75 Units",
    "page": 42,
    "image": "images/catalog/bags-abuja-tech-sleeve-17.jpg"
  },
  {
    "id": 49,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Lusaka Tech Backpack",
    "description": "Lusaka Upstyled",
    "material": "D600 And 170gsm",
    "size": "270 x 400 x 110mm (L x H x W)",
    "moq": "25 Units",
    "page": 43,
    "image": "images/catalog/bags-lusaka-tech-backpack.jpg"
  },
  {
    "id": 50,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Adelaide Maxi Kit Sport Bag",
    "description": "Adelaide Upstyled",
    "material": "D600 And 170gsm",
    "size": "500 x 290 x 250mm (L x H x W)",
    "moq": "25 Units",
    "page": 44,
    "image": "images/catalog/bags-adelaide-maxi-kit-sport-bag.jpg"
  },
  {
    "id": 51,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Perth Barrel Sport Bag",
    "description": "Perth Upstyled",
    "material": "D600 And 170gsm",
    "size": "520 x 250 x 250mm (L x H x W)",
    "moq": "25 Units",
    "page": 45,
    "image": "images/catalog/bags-perth-barrel-sport-bag.jpg"
  },
  {
    "id": 52,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Fiji Double-Sided Luggage Strap",
    "description": "Strap Glide",
    "material": "25mm Sublimated",
    "size": "1550mm x 50mm (L x W)",
    "moq": "75 Units",
    "page": 46,
    "image": "images/catalog/bags-fiji-double-sided-luggage-strap.jpg"
  },
  {
    "id": 53,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Tokyo Bag Double-Sided Strap",
    "description": "Luggage Not Included",
    "material": "25mm Or 38mm",
    "size": "1200mm x 25mm (L x W)",
    "moq": "75 Units",
    "page": 47,
    "image": "images/catalog/bags-tokyo-bag-double-sided-strap.jpg"
  },
  {
    "id": 54,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Blu Mini-Midi Double-Sided Dog Bandana",
    "description": "Blu Mini-Midi Upstyled",
    "material": "Lightweight 100% Polyester",
    "size": "480 x 200mm (L x H)",
    "moq": "75 Units",
    "page": 48,
    "image": "images/catalog/bags-blu-mini-midi-double-sided-dog-bandana.jpg"
  },
  {
    "id": 55,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Ibiza Travel Wallet",
    "description": "Ibiza Upstyled",
    "material": "170gsm",
    "size": "250 x 145mm (L x H)",
    "moq": "100 Units",
    "page": 49,
    "image": "images/catalog/bags-ibiza-travel-wallet.jpg"
  },
  {
    "id": 56,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Wall Street Maxi Coin Purse",
    "description": "Wall Street Maxi Upstyled",
    "material": "170gsm",
    "size": "170 x 100mm (L x H)",
    "moq": "100 Units",
    "page": 50,
    "image": "images/catalog/bags-wall-street-maxi-coin-purse.jpg"
  },
  {
    "id": 57,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Utah Mini Toiletry Bag",
    "description": "Utah Mini Upstyled",
    "material": "170gsm",
    "size": "150 x 150 x 30mm (L x H x W)",
    "moq": "100 Units",
    "page": 51,
    "image": "images/catalog/bags-utah-mini-toiletry-bag.jpg"
  },
  {
    "id": 58,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Utah Maxi Toiletry Bag",
    "description": "Utah Maxi Upstyled",
    "material": "170gsm",
    "size": "240 x 200 x 60mm (L x H x W)",
    "moq": "100 Units",
    "page": 52,
    "image": "images/catalog/bags-utah-maxi-toiletry-bag.jpg"
  },
  {
    "id": 59,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Madrid Toiletry Bag",
    "description": "Madrid Upstyled",
    "material": "D600 And 170gsm",
    "size": "240 x 120 x 140mm (L x H x W)",
    "moq": "100 Units",
    "page": 53,
    "image": "images/catalog/bags-madrid-toiletry-bag.jpg"
  },
  {
    "id": 60,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Brasilia Toiletry Bag",
    "description": "Brasilia Upstyled",
    "material": "170gsm",
    "size": "225 x 110 x 120mm (L x H x W)",
    "moq": "100 Units",
    "page": 54,
    "image": "images/catalog/bags-brasilia-toiletry-bag.jpg"
  },
  {
    "id": 61,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Lille Toiletry Bag",
    "description": "Lille Upstyled",
    "material": "170gsm",
    "size": "230 x 140 x 100mm (L x H x W)",
    "moq": "100 Units",
    "page": 55,
    "image": "images/catalog/bags-lille-toiletry-bag.jpg"
  },
  {
    "id": 62,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Cairo Mini Cosmetic Bag",
    "description": "Cairo Mini Upstyled",
    "material": "170gsm",
    "size": "210 x 140 x 75mm (L x H x W)",
    "moq": "100 Units",
    "page": 56,
    "image": "images/catalog/bags-cairo-mini-cosmetic-bag.jpg"
  },
  {
    "id": 63,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Cairo Midi Cosmetic Bag",
    "description": "Cairo Midi Upstyled",
    "material": "170gsm",
    "size": "250 x 160 x 85mm (L x H x W)",
    "moq": "100 Units",
    "page": 57,
    "image": "images/catalog/bags-cairo-midi-cosmetic-bag.jpg"
  },
  {
    "id": 64,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Cairo Maxi Cosmetic Bag",
    "description": "Cairo Maxi Upstyled",
    "material": "170gsm",
    "size": "310 x 210 x 105mm (L x H x W)",
    "moq": "100 Units",
    "page": 58,
    "image": "images/catalog/bags-cairo-maxi-cosmetic-bag.jpg"
  },
  {
    "id": 65,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Delhi Mini Cosmetic Bag",
    "description": "Delhi Mini Upstyled",
    "material": "170gsm",
    "size": "190 x 120 x 50mm (L x H x W)",
    "moq": "100 Units",
    "page": 59,
    "image": "images/catalog/bags-delhi-mini-cosmetic-bag.jpg"
  },
  {
    "id": 66,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Delhi Midi Cosmetic Bag",
    "description": "Delhi Midi Upstyled",
    "material": "170gsm",
    "size": "250 x 150 x 80mm (L x H x W)",
    "moq": "100 Units",
    "page": 60,
    "image": "images/catalog/bags-delhi-midi-cosmetic-bag.jpg"
  },
  {
    "id": 67,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Delhi Maxi Cosmetic Bag",
    "description": "Berlin Maxi Upstyled",
    "material": "170gsm",
    "size": "280 x 175 x 100mm (L x H x W)",
    "moq": "100 Units",
    "page": 61,
    "image": "images/catalog/bags-delhi-maxi-cosmetic-bag.jpg"
  },
  {
    "id": 68,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Bali Halfmoon Cosmetic Bag",
    "description": "Bali Upstyled",
    "material": "170gsm",
    "size": "220 x 110mm (L x H)",
    "moq": "100 Units",
    "page": 62,
    "image": "images/catalog/bags-bali-halfmoon-cosmetic-bag.jpg"
  },
  {
    "id": 69,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Monaco Mini Powder Pouch",
    "description": "Monaco Upstyled",
    "material": "170gsm",
    "size": "110 x 100mm (L x H)",
    "moq": "100 Units",
    "page": 63,
    "image": "images/catalog/bags-monaco-mini-powder-pouch.jpg"
  },
  {
    "id": 70,
    "source": "Upstyled Bags Catalogue_2026_02_20_V4_LQ (1).pdf",
    "category": "Bags and Travel",
    "name": "Saint-Tropez Round Base Cosmetic Bag",
    "description": "Saint-Tropez Upstyled",
    "material": "170gsm",
    "size": "200 x 280 x 200mm (L x H x W)",
    "moq": "50 Units",
    "page": 64,
    "image": "images/catalog/bags-saint-tropez-round-base-cosmetic-bag.jpg"
  },
  {
    "id": 71,
    "source": "Email Promo - New Display Products (6 March 2026) ..pdf",
    "category": "Displays",
    "name": "Balloon Banner",
    "description": "Small, medium, and large balloon display banners.",
    "material": "Stretch Polyester; aluminium pole; fibreglass",
    "size": "Small: 850 x 1200mm; Medium: 900 x 1600mm; Large: 900 x 1900mm",
    "moq": "",
    "page": 1,
    "image": "images/catalog/display-balloon-banner.jpg"
  },
  {
    "id": 72,
    "source": "Email Promo - New Display Products (6 March 2026) ..pdf",
    "category": "Displays",
    "name": "Flare Arch Banner",
    "description": "Large branded arch for events and activations.",
    "material": "Stretch Polyester; fibreglass rods; steel base",
    "size": "4000 x 2700mm",
    "moq": "",
    "page": 1,
    "image": "images/catalog/display-flare-arch-banner.jpg"
  },
  {
    "id": 73,
    "source": "Email Promo - New Display Products (6 March 2026) ..pdf",
    "category": "Displays",
    "name": "Event Bin",
    "description": "Functional branded event bin.",
    "material": "Oxford; fibreglass",
    "size": "700 x 850mm",
    "moq": "",
    "page": 1,
    "image": "images/catalog/display-event-bin.jpg"
  },
  {
    "id": 74,
    "source": "Email Promo - New Display Products (6 March 2026) ..pdf",
    "category": "Displays",
    "name": "Arch Feather Banner",
    "description": "Arch feather banner for sport, events, and outdoor visibility.",
    "material": "Ultrasheen; fibreglass rods; cross base",
    "size": "3800 x 2700mm",
    "moq": "",
    "page": 1,
    "image": "images/catalog/display-arch-feather-banner.jpg"
  },
  {
    "id": 75,
    "source": "Email Promo - New Display Products (6 March 2026) ..pdf",
    "category": "Displays",
    "name": "Directors Chair",
    "description": "Branded steel director chair with back, seat, or full branding options.",
    "material": "Gazebo Canvas; steel frame",
    "size": "440 x 480 x 780mm",
    "moq": "",
    "page": 1,
    "image": "images/catalog/display-directors-chair.jpg"
  },
  {
    "id": 76,
    "source": "Email Promo - Put Your Clients' Brands on Every Desk With Custom Notebooks & Diaries.pdf",
    "category": "Notebooks and Diaries",
    "name": "Jotly Full Colour Laminated Notebook",
    "description": "A4 full-colour laminated notebook with branded cover and custom insert options.",
    "material": "Un-padded cover",
    "size": "A4",
    "moq": "",
    "page": 1,
    "image": "images/catalog/notebook-jotly-full-colour-laminated-notebook.jpg"
  },
  {
    "id": 77,
    "source": "Email Promo - Put Your Clients' Brands on Every Desk With Custom Notebooks & Diaries.pdf",
    "category": "Notebooks and Diaries",
    "name": "Halo Full Colour Laminated Notebook",
    "description": "A5 wire-bound laminated notebook with customisation options.",
    "material": "Un-padded cover",
    "size": "A5",
    "moq": "",
    "page": 1,
    "image": "images/catalog/notebook-halo-full-colour-laminated-notebook.jpg"
  },
  {
    "id": 78,
    "source": "Email Promo - Put Your Clients' Brands on Every Desk With Custom Notebooks & Diaries.pdf",
    "category": "Notebooks and Diaries",
    "name": "Quill Full-Colour Laminated Diary",
    "description": "A4 full-colour laminated diary with branded pages and optional extras.",
    "material": "Un-padded cover",
    "size": "A4",
    "moq": "",
    "page": 1,
    "image": "images/catalog/notebook-quill-full-colour-laminated-diary.jpg"
  },
  {
    "id": 79,
    "source": "Email Promo - Put Your Clients' Brands on Every Desk With Custom Notebooks & Diaries.pdf",
    "category": "Notebooks and Diaries",
    "name": "Rolla Full-Colour Padded Laminated Diary",
    "description": "A4 padded laminated diary with branded cover, ribbons, and optional metal corners.",
    "material": "Padded cover",
    "size": "A4",
    "moq": "",
    "page": 1,
    "image": "images/catalog/notebook-rolla-full-colour-padded-laminated-diary.jpg"
  },
  {
    id: 9001,
    source: "Company Profile",
    category: "Printing Services",
    name: "Screen Printing",
    description: "Bulk garment printing for promotions, uniforms, festivals, and merchandise.",
    material: "Premium inks & garments",
    size: "Bulk orders available",
    moq: "50 Units",
    page: 5,
    image: "images/services/screen-printing.jpg"
},

{
    id: 9002,
    source: "Company Profile",
    category: "Printing Services",
    name: "DTF Printing",
    description: "Direct to Film printing for complex full-colour garment designs.",
    material: "DTF Transfer Film",
    size: "Custom sizing",
    moq: "10 Units",
    page: 5,
    image: "images/services/dtf-printing.jpg"
},

{
    id: 9003,
    source: "Company Profile",
    category: "Printing Services",
    name: "Embroidery",
    description: "Professional embroidery for caps, jackets, polos, uniforms, and apparel.",
    material: "Thread embroidery",
    size: "Custom sizing",
    moq: "10 Units",
    page: 5,
    image: "images/services/embroidery.jpg"
},

{
    id: 9004,
    source: "Company Profile",
    category: "Printing Services",
    name: "Laser Engraving",
    description: "Precision engraving for leather, denim, gifts, and branded products.",
    material: "Laser engraved finish",
    size: "Custom",
    moq: "5 Units",
    page: 5,
    image: "images/services/laser-engraving.jpg"
},

{
    id: 9005,
    source: "Company Profile",
    category: "Event Branding",
    name: "Branded Gazebos",
    description: "Custom branded gazebos for activations, expos, festivals, and outdoor events.",
    material: "Weather resistant fabric",
    size: "Custom",
    moq: "1 Unit",
    page: 6,
    image: "images/services/gazebo.jpg"
},

{
    id: 9006,
    source: "Company Profile",
    category: "Event Branding",
    name: "Event Flags & Banners",
    description: "Promotional banners, feather flags, and event signage.",
    material: "Full colour print",
    size: "Custom sizes",
    moq: "1 Unit",
    page: 6,
    image: "images/services/event-flags.jpg"
},

{
    id: 9007,
    source: "Company Profile",
    category: "Event Production",
    name: "LED Screens",
    description: "Large scale LED screen rentals for events, conferences, and festivals.",
    material: "Indoor & outdoor LED panels",
    size: "Custom configurations",
    moq: "1 Booking",
    page: 7,
    image: "images/services/led-screen.jpg"
},

{
    id: 9008,
    source: "Company Profile",
    category: "Event Production",
    name: "Professional Sound Systems",
    description: "Bose Professional DeltaQ sound systems for concerts and corporate events.",
    material: "Bose DeltaQ",
    size: "Venue dependent",
    moq: "1 Booking",
    page: 7,
    image: "images/services/sound-system.jpg"
},

{
    id: 9009,
    source: "Company Profile",
    category: "Event Production",
    name: "Stage & Lighting Production",
    description: "Full event staging, rigging, lighting design, and technical production.",
    material: "Professional staging systems",
    size: "Custom event setup",
    moq: "1 Booking",
    page: 7,
    image: "images/services/stage-lighting.jpg"
},

{
    id: 9010,
    source: "Company Profile",
    category: "Event Production",
    name: "Live Streaming",
    description: "Professional multi-camera live streaming for conferences and events.",
    material: "HD broadcast equipment",
    size: "Custom setup",
    moq: "1 Booking",
    page: 7,
    image: "images/services/live-streaming.jpg"
}
];
